######################################################################
# Automatically generated by qmake (2.01a) ven. 23. mai 16:31:10 2008
######################################################################
QT += widgets
TEMPLATE = app
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += FenCodeGenere.h FenPrincipale.h
SOURCES += FenCodeGenere.cpp FenPrincipale.cpp main.cpp
